= Running SPEC CPU2017 in C3 gem5

This document describes how to use scripts to run SPEC CPU2017 benchmarks on C3 gem5. +
First, we modify the SPEC CPU2017 configuration file to build benchmark binaries compatible with C3 gem5 and then we launch these benchmarks with the scripts provided.

NOTE: SPEC benchmark source code is not included in this software distribution.

NOTE: Benchmark results might vary depending on the versions of the component binaries installed inside the docker._

'''

=== Preparing SPEC CPU2017 configuration file
Make the following changes in the example configuration file provided with the SPEC CPU2017 installation --

. Define the build label `label` as `"intel_spec_simpoints"` _(line#58)_. +
Set the `label` variable to `%{label}-m%{bits}` _(line#96)_

. Define gcc path `gcc_dir` as `"/usr"` _(line#154)_

. Append `peak` to the tune variable `tune` _(line#104)_. Set it to `base,peak` +
    Set Base Tuning Flags `OPTIMIZE` to `-g -O1 -march=x86-64` _( line#310)_ +
    Set Peak Tuning Flags `OPTIMIZE` to `-g -Ofast -march=x86-64 -flto` _(line#315)_

. *Link the built binaries with our custom C3 glibc and disable vector instructions* +
.. Append the following flags in `PORTABILITY` and `CPORTABILITY` variables _(lines #206, #213 and #216)_

    -L /c3-perf-simulator/c3-simulator/glibc/glibc-2.30_install/lib -I /c3-perf-simulator/c3-simulator/glibc/glibc-2.30_install/include -Wl,--rpath=/c3-perf-simulator/c3-simulator/glibc/glibc-2.30_install/lib -Wl,--dynamic-linker=/c3-perf-simulator/c3-simulator/glibc/glibc-2.30_install/lib/ld-linux-x86-64.so.2 -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mno-avx512vbmi2 -mno-avx512vnni -mno-avx512bitalg -mno-avx512vpopcntdq -mno-sse4a -mno-avx -mno-sse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -mno-sse4 -static

.. Append the following flags in the `PORTABILITY` and `CPORTABILITY` variables _(lines #209, #219 and #222)_

    -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mno-avx512vbmi2 -mno-avx512vnni -mno-avx512bitalg -mno-avx512vpopcntdq -mno-sse4a -mno-avx -mno-sse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -mno-sse4 -static

.. Add the following code in the `default` portability case statement +

    PORTABILITY = -L /c3-perf-simulator/c3-simulator/glibc/glibc-2.30_install/lib -I /c3-perf-simulator/c3-simulator/glibc/glibc-2.30_install/include -Wl,--rpath=/c3-perf-simulator/c3-simulator/glibc/glibc-2.30_install/lib -Wl,--dynamic-linker=/c3-perf-simulator/c3-simulator/glibc/glibc-2.30_install/lib/ld-linux-x86-64.so.2 -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mno-avx512vbmi2 -mno-avx512vnni -mno-avx512bitalg -mno-avx512vpopcntdq -mno-sse4a -mno-avx -mno-sse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -mno-sse4 -static

. Append the entire contents of *tests/simpoint/spec_peak_hashes.txt* to the end of this configuration file.

. Save this configuration file as *tests/simpoint/c3-spec-config.cfg*

NOTE: The changes to PORTABILITY are necessary to disable gcc from generating vector instructions during compilation. The gem5 simulator currently does not support Advanced Vector Extensions (AVX) which are a set of SIMD extensions to the x86 instruction set architecture.

'''

=== Running SPEC CPU2017

. *Preparing your SPEC CPU2017 Installation* +
  If not installed already, follow the guide https://www.spec.org/cpu2017/Docs/install-guide-unix.html[here] to setup your copy of SPEC CPU2017. +
  The SPEC installation path will be required in the next step.

. *Running Docker with SPEC CPU2017* +
..  Build the docker image using the *build_docker.sh* script as mentioned above and exit the docker once it launches.
..  Execute the *run_docker_with_SPEC.sh* script passing the path to your SPEC installation as an argument as follows: +
    `./run_docker_with_SPEC.sh <Path/to/SPEC2017>` +
    This will mount the SPEC CPU2017 installation directory in the docker at /spec2017 and attach to the docker shell.
. *Preparing SPEC binaries* +
..  The first task to be done now is modifying the SPEC CPU2017 example configuration file. See the section below on how to proceed.
..  Once the required modifications are done, run prep_spec_run.sh to build and run the SPEC benchmarks at least once inside the docker. +
    This generates the required directory structure inside the docker to execute these benchmarks with gem5. +
    It also clones and builds pinplay-tools, which is required to collect simpoints.
. *Running SPEC CPU2017 with gem5* +
    Inside the docker, run the *run_SPEC_benchmarks.sh* script to execute the benchmarks with gem5. +
    This is a 4 step process and can take a considerable amount of time (even days), depending on the number of instructions being run for. +
..  The steps are as follows:-
...     _Generating BBV (Block base vector)_ +
            Generate the BBV for the benchmark using SimpleAtomicCPU.
...     _Generating Simpoint weights from BBV_ +
...     _Taking checkpoints_ +
            Run the benchmarks with gem5 again to collect the checkpoints as described in the simpoints generated by the previous step.
...     _Running gem5 from checkpoints_ +
            Run gem5 from collected checkpoints using C3 CPU +
            The max number of instructions gem5 should run to is given as an argument to the script.
