= C3 gem5-based Performance Simulator

[.lead]
This is an experimental performance simulator for Cryptographic Capability Computing (C3).

NOTE: If NOT running gem5 inside the provided docker, clone this repository with --recurse-submodules - otherwise, many tests will not build.

== Building and Testing C3 gem5
To build, run, and test the simulator inside a controlled Docker environment, follow the following steps:

.   *Run build_docker.sh* +
    This script builds the c3-gem5-docker docker image, which has a copy of the gem5 source code and the run_blowfish test script. +
    Once the docker image is built, a container will be spawned and the shell will be transferred to the running container.
.   *Run run_blowfish.sh inside the docker container* +
    This script builds the blowfish test and runs it in inside gem5 in five configurations. The results are then summarized for comparison. +
    The configurations are as listed: +
..      *RUN0*:	No C3
..      *RUN1*:	C3, Heap addresses encryption   , No PredTLB
..      *RUN2*:	C3, All addresses encryption    , No PredTLB
..      *RUN3*:	C3, Heap addresses encryption   , PredTLB
..      *RUN4*:	C3, All addresses encryption    , PredTLB

The Docker image will have an operational copy of C3 gem5 and can be used for further testing and demonstration as required.

We have a batch of tests to verify basic functionality of the gem5-based C3 performance simulator. +
To run a these tests, follow the steps below: +

.   *CMD*:  cd tests/c3_tests
.   *CMD*:  yes | make test +
    This will build gem5 and the custom GLIBC (both already built inside the docker) and run our tests.


We are also including scripts to run *_SPEC CPU2017_* benchmarks on C3 gem5 for reproducing the results we have reported. +
Please note that the results were obtained for specific versions of the binaries installed inside the docker,
and might change if any other version is used. Read link:README_SPEC.adoc[] for a detailed description of the steps to run these benchmarks.

NOTE: The Dockerfile uses fixed versions for the base image and certain packages necessary for building C3 gem5 reliably. These versions of base image and packages might become unavailable in the future and would have to be updated manually. +
To update the Docker base image, replace the _digest_ in the first line in the Dockerfile (FROM ...) with one corresponding to an available base image. Alternatively, it's possible to use something like `FROM mcr.microsoft.com/devcontainers/base:ubuntu-20.04` to skip looking for a relevant _digest_. +
To update the fixed packages, simply update the version mentioned in the Dockerfile in the `apt-get install` command.

'''

_The contents of this repository and linked repositories are solely for research purposes and may contain software with vulnerabilities, such as outdated libraries. Do not use in production._

_This material is based upon work supported by the Naval Information Warfare Center Pacific and the Defense Advanced Research Project Agency under Prototype Other Transaction Agreement No. N66001-23-9-4004. Any opinions, findings and conclusions or recommendations expressed in this material are those of the author(s) and do not necessarily reflect the views of the Naval Information Warfare Center Pacific or the Defense Advanced Research Project Agency_

'''
